# Generated by Django 4.2.2 on 2023-06-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carimg', models.ImageField(upload_to='pic')),
                ('carname', models.CharField(max_length=60)),
                ('carDesi', models.CharField(max_length=60)),
                ('carPrice', models.CharField(max_length=30)),
            ],
        ),
    ]
